### ISSUE TITLE
Animalia crash due to frogs

### ISSUE THREAD

**Issue by DetermiedMech1** [FlinTyX/Animalia#13]
###### @FlinTyX , the guy that will try to fix your issue
hi flin
---

**Issue**: *Explain your issue in detail.*
I am encountering a crash whenever a frog is made using the incubator

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
I was making a factory for frogs when unexpectedly, the game crashed as soon as one of the frogs hatched
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [x] **I have updated to the latest release (https://github.com/FlinTyX/Animalia/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

###### Latest crash found:
```
Crash: 03_26_2023_14_12_25.txt

Mindustry has crashed. How unfortunate.
Version: release build 141.2
OS: Windows 10 x64 (amd64)
Java Version: 16.0.1
Runtime Available Memory: 4062mb
Cores: 16
Mods: animalia:java 1.0, byte-logic-mod:v1.2.1, challenge:1.0, erek:0.3, erekir-junction:1, erekir-logic:Release V1, erekir-utilities:0.3, gas-fix:1.1, lighting:0.3 Pre-Alpha, mega-build:Fix update, prog-mats:26.6, test-utils:48, time-control:0.2, tranqol:v2, yr2-logic-debugger:1.6.4

java.lang.NoClassDefFoundError: animalia/entities/units/FrogEntity
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
	at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
	at rhino.DefiningClassLoader.defineClass(DefiningClassLoader.java:19)
	at rhino.JavaAdapter.loadAdapterClass(JavaAdapter.java:427)
	at rhino.JavaAdapter.getAdapterClass(JavaAdapter.java:249)
	at rhino.JavaAdapter.js_createAdapter(JavaAdapter.java:160)
	at rhino.JavaAdapter.execIdCall(JavaAdapter.java:73)
	at rhino.IdFunctionObject.call(IdFunctionObject.java:81)
	at rhino.ScriptRuntime.applyOrCall(ScriptRuntime.java:2374)
	at rhino.BaseFunction.execIdCall(BaseFunction.java:334)
	at rhino.IdFunctionObject.call(IdFunctionObject.java:81)
	at rhino.optimizer.OptRuntime.call2(OptRuntime.java:32)
	at rhino.gen.global_js_1._c_extend_13(global.js:33)
	at rhino.gen.global_js_1.call(global.js)
	at rhino.optimizer.OptRuntime.callName(OptRuntime.java:51)
	at rhino.gen.main_js_7._c_anonymous_20(main.js:115)
	at rhino.gen.main_js_7.call(main.js)
	at rhino.ContextFactory.doTopCall(ContextFactory.java:328)
	at rhino.ScriptRuntime.doTopCall(ScriptRuntime.java:3114)
	at rhino.gen.main_js_7.call(main.js)
	at rhino.ArrowFunction.call(ArrowFunction.java:33)
	at rhino.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:141)
	at rhino.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:92)
	at rhino.Context.call(Context.java:450)
	at rhino.ContextFactory.call(ContextFactory.java:428)
	at rhino.InterfaceAdapter.invoke(InterfaceAdapter.java:92)
	at rhino.VMBridge.lambda$newInterfaceProxy$0(VMBridge.java:142)
	at jdk.proxy1/jdk.proxy1.$Proxy1.get(Unknown Source)
	at mindustry.type.UnitType.create(UnitType.java:444)
	at animalia.world.units.Incubator$IncubatorBuild.hatch(Incubator.java:146)
	at animalia.world.units.Incubator$IncubatorBuild.updateTile(Incubator.java:205)
	at mindustry.gen.Building.update(Building.java:2144)
	at mindustry.entities.EntityGroup.update(EntityGroup.java:83)
	at mindustry.gen.Groups.update(Groups.java:83)
	at mindustry.core.Logic.update(Logic.java:466)
	at arc.ApplicationCore.update(ApplicationCore.java:37)
	at mindustry.ClientLauncher.update(ClientLauncher.java:230)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:204)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:192)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
Caused by: java.lang.ClassNotFoundException: animalia.entities.units.FrogEntity
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at rhino.DefiningClassLoader.loadClass(DefiningClassLoader.java:32)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 42 more

```

**Comment by FlinTyX** [comment]
Sorry @DetermiedMech1, I'm not able to recreate your issue.
A video of the crash happening would be useful.

**Comment by DetermiedMech1** [comment]
I haven't seen anything happening since so it may have just been my device.

**Comment by FlinTyX** [comment]
Thank you for reporting the issue anyway. Sorry for this.
Animalia is currently being updated, so wait new content in the next weeks...
