### ISSUE TITLE
Crash issue

### ISSUE THREAD

**Issue by Roughlygoodname** [FlinTyX/Animalia#7]
Mindustry has crashed. How unfortunate.
Version: pre-alpha build 135
OS: Windows 10 x64 (amd64)
Java Version: 16.0.1
Mods: animalia:0.1.2

java.lang.NullPointerException: Cannot read field "windVector" because the return value of "mindustry.type.Weather.create(float, float)" is null
	at mindustry.type.Weather.createWeather(Weather.java:278)
	at mindustry.gen.Call.createWeather(Call.java:264)
	at mindustry.core.Logic.updateWeather(Logic.java:263)
	at mindustry.core.Logic.update(Logic.java:389)
	at arc.ApplicationCore.update(ApplicationCore.java:37)
	at mindustry.ClientLauncher.update(ClientLauncher.java:177)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:166)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:154)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:45)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)

**Comment by FlinTyX** [comment]
https://github.com/FlinTyX/Animalia/commit/f68344766e92c5b538c34712f4b27d53bba0f2c0
